identifier: Oceanservice
title: Oceanservice
team: 
  - service_team
blueprint: service
properties:
  workload_short: scim
  language: java
  deployment_zone: private
  net_version: net8.2
  readme: file://./README.md
