identifier: Oceanservice
title: Oceanservice
team: 
  - service_team
blueprint: service
properties:
  workload_short: sci
  language: java
  deployment_zone: private
  net_version: net8.5
  readme: file://./README.md
relations:
  calcserv: priya_calculation_service
